/* SPDX-License-Identifier: PolyForm-Noncommercial-1.0.0 - see LICENSE.md */
/* Generates ai/ai_preflop_data.h: the equity of each of the 169 starting-hand
   classes against one and against three random hands, by Monte Carlo with a
   fixed seed (so the output is reproducible), 400,000 trials per class and
   opponent count (standard error under 0.08 percentage points).

       ./build/ai_gen_preflop ai/ai_preflop_data.h

   The AI ranks starting hands from these numbers at start-up; rerun this only
   if the equity code changes. tests/ai/test_ai_equity.c re-checks a sample. */

#include "ai/ai.h"

#include <stdio.h>
#include <stdlib.h>

#define GEN_TRIALS 400000
#define GEN_SEED   0x42656573ull     /* any fixed value; recorded in the file */

static void rep(int cls, Card h[2])
{
  int row = cls / 13, col = cls % 13;
  if (row == col) {
    h[0] = card_make(row, SUIT_C); h[1] = card_make(row, SUIT_D);
  } else if (row > col) {            /* suited: hi*13 + lo */
    h[0] = card_make(row, SUIT_S); h[1] = card_make(col, SUIT_S);
  } else {                           /* offsuit: lo*13 + hi */
    h[0] = card_make(col, SUIT_S); h[1] = card_make(row, SUIT_H);
  }
}

int main(int argc, char **argv)
{
  static int eq1[AI_NCLASSES], eq3[AI_NCLASSES];
  FILE *f;
  Rng r;
  int c;

  if (argc != 2) {
    fprintf(stderr, "usage: %s <output.h>\n", argv[0]);
    return 2;
  }
  ai_init();
  rng_seed(&r, GEN_SEED);
  for (c = 0; c < AI_NCLASSES; c++) {
    Card h[2];
    char name[4];
    rep(c, h);
    eq1[c] = (int)(ai_equity(h, NULL, 0, 1, NULL, GEN_TRIALS, &r) * 10000.0 + 0.5);
    eq3[c] = (int)(ai_equity(h, NULL, 0, 3, NULL, GEN_TRIALS, &r) * 10000.0 + 0.5);
    fprintf(stderr, "%-4s %6.2f%% %6.2f%%\n", ai_class_name(c, name), eq1[c] / 100.0, eq3[c] / 100.0);
  }
  f = fopen(argv[1], "w");
  if (!f) { perror(argv[1]); return 1; }
  fprintf(f, "/* SPDX-License-Identifier: PolyForm-Noncommercial-1.0.0 - see LICENSE.md */\n");
  fprintf(f, "/* Generated by tools/ai_gen_preflop.c (seed 0x%llx, %d trials per entry).\n",
          (unsigned long long)GEN_SEED, GEN_TRIALS);
  fprintf(f, "   Do not edit: rerun the tool. Equity x 10000 of each starting-hand class\n");
  fprintf(f, "   (index as ai_hand_class) against one and three random hands. */\n");
  fprintf(f, "#ifndef BPL_AI_PREFLOP_DATA_H\n#define BPL_AI_PREFLOP_DATA_H\n\n");
  fprintf(f, "static const uint16_t AI_PF_EQ1[169] = {");
  for (c = 0; c < AI_NCLASSES; c++) fprintf(f, "%s%d,", c % 13 ? " " : "\n  ", eq1[c]);
  fprintf(f, "\n};\n\nstatic const uint16_t AI_PF_EQ3[169] = {");
  for (c = 0; c < AI_NCLASSES; c++) fprintf(f, "%s%d,", c % 13 ? " " : "\n  ", eq3[c]);
  fprintf(f, "\n};\n\n#endif\n");
  fclose(f);
  return 0;
}
